### ISSUE TITLE
Error when calling django tests

### ISSUE THREAD

**Issue by frayel** [jcass77/django-apscheduler#125] opened 2020-11-05 12:43 UTC
Created a simple test, with setup to create all databases on test:

class MyTestCase(TestCase):
    databases = '__all__'

    def test(self):
        print('test')

And tried to run:
python manage.py test

Giving the error:

at

 File "H:\OneDrive\Documents\Workspace\workspace.python\executorbpm\venv\lib\site-packages\django_apscheduler\migrations\0005_migrate_name_to_id.py", line 14, in migrate_name_to_id
    for job in JobModel.objects.all():

Error:
 django.db.utils.OperationalError: no such column: django_apscheduler_djangojob.name

**Comment by jcass77** [comment] 2020-11-05 14:02
The tests run successfully as part of this project’s continuous integration workflow so can’t think of any potential issues there.

Have you tried running the tests with `pytest` instead of the management command?

**Comment by frayel** [comment] 2020-11-05 14:39
Well, i think could be someting related with my enviroment.

**Comment by jcass77** [comment] 2020-11-06 03:18
Closing for now, please re-open if you find the root cause to be in django-apscheduler.

**Closed as completed by jcass77** 2020-11-06 03:18 UTC

**Comment by Carnagie** [comment] 2021-12-14 17:02
For any of you wondering how to skip this migrations fail in test environments you can add this to your test settings
`MIGRATION_MODULES = {
    'django_apscheduler': None
}`
