### ISSUE TITLE
DjangoJobExecution.MultipleObjectsReturned: get() returned more than one DjangoJobExecution

### ISSUE THREAD

**Issue by cysnet** [jcass77/django-apscheduler#129] opened 2020-12-23 15:30 UTC
Error notifying listener
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 831, in _dispatch_event
    cb(event)
  File "/usr/local/lib/python3.8/site-packages/django_apscheduler/jobstores.py", line 49, in handle_submission_event
    job_execution = DjangoJobExecution.atomic_update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django_apscheduler/models.py", line 156, in atomic_update_or_create
    job_execution = DjangoJobExecution.objects.select_for_update().get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
django_apscheduler.models.DjangoJobExecution.MultipleObjectsReturned: get() returned more than one DjangoJobExecution -- it returned 2!

**Comment by jcass77** [comment] 2020-12-24 03:25
The creation of `DjangoJobExecution` instances is protected by a reentrant thread lock. If you are seeing duplicates being created in your database then it might mean that you have django-apscheduler running in multiple threads.

Please check the README section and confirm that you are starting up only one instance of django-apscheduler using a custom Django management command?

**Comment by jcass77** [comment] 2020-12-28 03:52
Closing on the assumption that this issue was caused by multiple Django worker threads running their own instances of `BackgroundScheduler` concurrently.

Please re-open if you are encountering this issue even with only one scheduler instance running in a single thread.

**Closed as completed by jcass77** 2020-12-28 03:52 UTC
