### ISSUE TITLE
error raised when run Django app with django-apscheduler

### ISSUE THREAD

**Issue by tangxingjun** [jcass77/django-apscheduler#96] opened 2020-08-05 15:57 UTC
python3.5+Django2.2.15  +   django-apscheduler 0.4.0 +Mysql 5.6.48（or 8.0.xx）
when run Django app with django-apscheduler ,error raised。I have no idea how to deal with this error。
django.db.utils.NotSupportedError: FOR UPDATE OF is not supported on this database backend.
![image](https://user-images.githubusercontent.com/32895309/89437240-e7e85880-d779-11ea-8b3c-da6e8983b421.png)
![image](https://user-images.githubusercontent.com/32895309/89434688-6ba04600-d776-11ea-912b-21eea3f1762d.png)

**Comment by jcass77** [comment] 2020-08-06 07:17
This looks like a duplicate of #94. The issue has since been resolved and will be included in the next release.

In the interim your options are to downgrade to v0.3.1 or use the most recent codebase from the main branch of this project.

**Closed as completed by jcass77** 2020-08-06 07:17 UTC

**Comment by tangxingjun** [comment] 2020-08-06 07:22
> This looks like a duplicate of #94. The issue has since been resolved and will be included in the next release.
> 
> In the interim your options are to downgrade to v0.3.1 or use the most recent codebase from the main branch of this project.

Sorry ,noted.Thanks
