### ISSUE TITLE
Error: no such table: django_apscheduler_djangojob

### ISSUE THREAD

**Issue by iHTCboy** [jcass77/django-apscheduler#108] opened 2020-09-11 06:55 UTC
In a project that has used django_apscheduler, executing` python manage.py migrate` will report this error:

```
django.db.utils.OperationalError:  no such table: django_apscheduler_djangojob
```

The reason is because the code already references the timing task of django_apscheduler, how can I solve this? thanks~

**Comment by jcass77** [comment] 2020-09-11 08:19
Could you outline the sequence of steps that you followed as well as the full exception stack trace?

The migrations that we have available at the moment should already provide safe passage for existing projects on releases prior to v0.4.0 so not sure what the root cause could be.

**Comment by iHTCboy** [comment] 2020-09-11 10:24
@jcass77 

APScheduler==3.6.3
django-apscheduler==0.4.2
Django==3.1

macOS 10.15.6


```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_apscheduler_djangojob

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/python_proj/python_proj/python_proj/urls.py", line 34, in <module>
    url(r'^SchedulerTask/', include('SchedulerTask.urls')),
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/python_proj/python_proj/SchedulerTask/urls.py", line 14, in <module>
    from .views import *
  File "/Volumes/python_proj/python_proj/SchedulerTask/views.py", line 186, in <module>
    scheduler1.start()
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/apscheduler/schedulers/background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 162, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 867, in _real_add_job
    store.add_job(job)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django_apscheduler/jobstores.py", line 209, in add_job
    return DjangoJob.objects.create(
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Volumes/python_proj/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_apscheduler_djangojob

```

**Comment by jcass77** [comment] 2020-09-11 11:25
I can't see anything obviously wrong in the stack trace provided. In general though if the migration expects to find a table in the DB that no longer exists then something must have happened at some point to cause the migrations and DB schema for your project to go out of sync.

The `django_apscheduler_djangojob` table has been in continuous use since the very start of django-apscheduler so the fact that it no longer exists in your local database is strange indeed.

You could try resetting your migrations, but it comes with some **risk of data loss**, and should only be used as a last resort. 

I have had good success in the past by following the steps in [this tutorial](https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html) by  Vitor Freitas (**use at your own risk!!**).

**Comment by iHTCboy** [comment] 2020-09-11 15:18
@jcass77  


I know why:
```
scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'default')

@register_job(scheduler, 'cron', hour=8, minute=30, replace_existing=True)
def delete_tmp_files():
    pass

scheduler.start()
```

remove that : `scheduler.start()`  ,  run `python manage.py migrate` is ok, so way?



I try to:

```
scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'default')

@register_job(scheduler, 'cron', hour=8, minute=30, replace_existing=True)
def delete_tmp_files():
    pass


try:
    scheduler.start()
except KeyboardInterrupt:
    scheduler.shutdown()
    print("Scheduler shut down successfully!")
```

Still no good, so way error?  thanks~

**Comment by jcass77** [comment] 2020-09-11 16:27
Where has the code above been defined? If it is being executed when you run `migrate` (it shouldn’t) then it must be being executed when your Python modules are being loaded or as part of Django’s `runserver` command?

This could cause issues when migrations are being run as the scheduler will want to start writing to the job store tables while the DB schema may still be in an inconsistent state. That would explain the exception you are seeing.

In my view there isn’t really a sensible way to run `BackgroundScheduler` in a Django app which is why I favor the approach of using `BlockingScheduler` combined with a custom management command as explained in this project’s README file.

**Comment by iHTCboy** [comment] 2020-09-12 02:47
@jarekwg  thanks reply~

in my way, want to do:

```

isExistTable = False
try:
   **TODO: check exist 'django_apscheduler_djangojob' table**
    isExistTable =True
except Exception as e:
    print(e)

if isExistTable:
    try:
        scheduler1.start()
    except Exception as e:
        scheduler1.shutdown()
        print("Scheduler shut down successfully!")
```


I want to know how to achieve it if there is a table it with code `TODO: check exist 'django_apscheduler_djangojob' table`, I did not find the Google, you know ? thanks~

**Comment by jcass77** [comment] 2020-09-12 04:29
I haven’t come across a database agnostic way of verifying table existence in Django. The assumption is that migrations will have executed successfully before Django is started up.

Closing this as the issue does not seem to be related to any bugs in django-apscheduler.

**Closed as completed by jcass77** 2020-09-12 04:29 UTC

**Comment by iHTCboy** [comment] 2020-09-14 01:35
@jcass77  thanks~

good job for me:

```
scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'default')

@register_job(scheduler, 'cron', hour=8, minute=30, replace_existing=True)
def delete_tmp_files():
    pass

isExistTable = False
try:
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('SELECT * FROM django_apscheduler_djangojob')
    cursor.close()
    isExistTable =True
except Exception as e:
    print(e)

if isExistTable:
    try:
        scheduler.start()
    except Exception as e:
        print(e)
        scheduler.shutdown()
        print("Scheduler shut down successfully!")
```


used `isExistTable` check 'django_apscheduler_djangojob' table,  after  run `python manage.py migrate`  is success！ thanks~

**Comment by dennohpeter** [comment] 2021-05-11 06:14
Ensure you have ⬇️ ⬇️ ⬇️ ⬇️  on your `settings.py`
```
import dj_database_url
...

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
```
