### ISSUE TITLE
Got error when looking for jobs to run.

### ISSUE THREAD

**Issue by BlackWatchuser** [jcass77/django-apscheduler#134] opened 2021-03-04 03:48 UTC
**here is the logs:**

`2021-03-04 10:54:32,191 [APScheduler:140570299115264]  [base:_process_jobs] [WARNING]- Error getting due jobs from job store 'default': (2006, 'MySQL server has gone away')`

**Description:**
1. JobStore: using DjangoJobStore()
 `jobstores = {
    'default': DjangoJobStore(),
}`
2. database: using MySQL. with wait_timeout=30min
3. job's running interval is over 30min.
so the mysql server closed connection, and when the job is exepected to run, i got An error from logs.

**Expected behavior**
Connection should reconnect to MySQL.

**Comment by jcass77** [comment] 2021-03-04 07:04
Duplicate of #128.

**Closed as completed by jcass77** 2021-03-04 07:04 UTC
Labels: duplicate

**Comment by BlackWatchuser** [comment] 2021-03-08 10:24
Thanks for reply firstly, so the soluation is:
do 
``` python
django.db import connection
connection.close()
```
in the front of every registered job, and so the Django will reopen the connection to avoid connection has been marked as  invalid, right ?
But, this error log mentioned above is ocurred in "getting due jobs from job store" stage, which is out of my code's control.

**Comment by jcass77** [comment] 2021-03-08 11:10
It is possible that this requires a patch somewhere in django-apscheduler to better support MySQL. Unfortunately I don't run MySQL locally so don't really have a working instance against which to troubleshoot.

There were some funky workarounds suggested in the past which included (a) pinging the MySQL server continuously to avoid it closing connections and (b) wrapping all DB calls in an exception handler of sorts :‑###..

See https://github.com/jcass77/django-apscheduler/issues/128#issuecomment-737058299 and https://github.com/jcass77/django-apscheduler/issues/79 for some ideas.

I would welcome a pull request if you are able to come up with an alternative that does not prejudice non-MySQL users in any way.

**Comment by BlackWatchuser** [comment] 2021-03-11 07:07
thanks for this solution.😊
