### ISSUE TITLE
mysql not support FOR UPDATE OF 

### ISSUE THREAD

**Issue by liu3734** [jcass77/django-apscheduler#94] opened 2020-07-30 02:53 UTC
When i use myqsl backends . raise this Exception
django_apscheduler/models.py at 155
![image](https://user-images.githubusercontent.com/8966977/88874953-d8857e80-d252-11ea-9220-46515c1fdb5a.png)
![image](https://user-images.githubusercontent.com/8966977/88874954-d9b6ab80-d252-11ea-9084-3a55fe7af516.png)

**Comment by jcass77** [comment] 2020-07-30 05:54
Duplicate of #93.

**Comment by jveeru** [comment] 2020-07-30 18:13
Can we open this one again? Because this is not duplicate as this issue is with MySQL not MSSQL. @jcass77

**Comment by jcass77** [comment] 2020-07-31 05:35
I was wrong, this isn't an exact duplicate of #93. As noted in that issue however, MySQL does not appear to support using the `of` parameter in [`select_for_update`](https://docs.djangoproject.com/en/3.0/ref/databases/#row-locking-with-queryset-select-for-update).

I think the parameter is probably superfluous in this case as we are not also selecting any related objects via `select_related` in the QuerySet, so we should be able to just remove it.

**Closed as completed** 2020-07-31 05:44 UTC
Labels: bug

**Comment by liu3734** [comment] 2020-07-31 05:52
Thanks @jcass77

**Comment by jveeru** [comment] 2020-07-31 15:12
Thanks @jcass77
